@baseUrl=http://localhost:3005

GET {{baseUrl}}/ HTTP/1.1

### Get versões de um componente
GET {{baseUrl}}/usuario HTTP/1.1

### Get versões de um componente
PUT {{baseUrl}}/usuario/0918c489-17ff-4748-83ac-512f46d7be55 HTTP/1.1
Content-Type: application/json

{
  "nome": "Edyardo",
  "email": "renan@com.com",
  "senha": "senhaSegura13"
}

### Get versões de um componente

POST {{baseUrl}}/usuario HTTP/1.1
Content-Type: application/json

{
  "nome": "Mario da Silva",
  "email": "renansilva@example.com",
  "senha": "senhaSegura123"
}

###GET produtos
GET {{baseUrl}}/produto HTTP/1.1
###POST produto
POST {{baseUrl}}/produto HTTP/1.1
Content-Type: application/json

{
    "usuarioId": "d3a812fd-63da-492e-841b-a6f285991ee5",
    "nome": "Figura de ação Marvel Homem Aranha Olympus Homem Aranha E6358 de Hasbro Classic",
    "valor": 70.0,
    "quantidade": 10,
    "descricao": "Produto novo, bem acabado, alegria para colecionadores",
    "caracteristicas": [{
        "nome": "Fabricante",
        "descricao": "Iron Studios"
    },{
        "nome": "material",
        "descricao": "Plástico"
    }],
    "imagens": [{
        "url": "https://i.imgur.com/dwDZICq.jpg",
        "descricao": "Imagem do Homem Aranha"
    }],
    "categoria": "Colecionáveis"
}