@baseUrl=http://localhost:3005

GET {{baseUrl}}/ HTTP/1.1

### Get versões de um componente
GET {{baseUrl}}/usuario HTTP/1.1

### Get versões de um componente
PUT {{baseUrl}}/usuario/46070e89-f001-4a2a-80f6-d0a70b41b18c HTTP/1.1
Content-Type: application/json

{
  "nome": "Edyardo",
  "email": "renan@com.com",
  "senha": "senhaSegura13"
}

### Get versões de um componente
POST {{baseUrl}}/usuario/ HTTP/1.1
Content-Type: application/json

{
  "nome": "Mario da Silva",
  "email": "renansilva@example.com",
  "senha": "senhaSegura123"
}

###GET produtos
GET {{baseUrl}}/produto HTTP/1.1
###POST produto
POST {{baseUrl}}/produto HTTP/1.1
Content-Type: application/json

{
    "usuarioId": "0eebd5dc-b91e-4552-b6da-297134e4e5a7",
    "nome": "Figura de ação Marvel Homem Aranha Olympus Homem Aranha E6358 de Hasbro Classic",
    "valor": 70.0,
    "quantidade": 10,
    "descricao": "Produto novo, bem acabado, alegria para colecionadores",
    "caracteristicas": [{
        "nome": "Fabricante",
        "descricao": "Iron Studios"
    },{
        "nome": "material",
        "descricao": "Plástico"
    }],
    "imagens": [{
        "url": "https://i.imgur.com/dwDZICq.jpg",
        "descricao": "Imagem do Homem Aranha"
    }],
    "categoria": "Colecionáveis"
}

### Delete usuario
DELETE  {{baseUrl}}/usuario/acb0d69f-4943-4e64-9bea-5a815e453786 HTTP/1.1
Content-Type: application/json

### Delete produto
DELETE  {{baseUrl}}/produto/a1940558-de6f-4ab3-8408-813db6f4d454 HTTP/1.1
Content-Type: application/json